import { Review } from "../models/Review.js";

const initialReviews = [
    {
        content: "Muy buena canción, el ritmo es demasiado pegajoso",
        likes: 12, 
        comments: 3, 
        rating: 5, 
        date: new Date(),
        username: "carlos23", 
        userId: 1, 
        songId: 1, 
        imageUrl: null,
    },
    {
        content: "La escuché por TikTok y ahora no puedo dejar de oírla",
        likes: 9, 
        comments: 2, 
        rating: 4, 
        date: new Date(),
        username: "lauramusic", 
        userId: 2, 
        songId: 1, 
        imageUrl: null,
    },
    {
        content: "Me gusta pero siento que ya la quemaron mucho",
        likes: 6, 
        comments: 1, 
        rating: 3, 
        date: new Date(),
        username: "andresgamer", 
        userId: 3, 
        songId: 1, 
        imageUrl: null,
    },
    {
        content: "La voz del artista es brutal, muy buena producción",
        likes: 15, 
        comments: 4, 
        rating: 5, 
        date: new Date(),
        username: "sofia_r", 
        userId: 4, 
        songId: 2, 
        imageUrl: null,
    },
    {
        content: "No es mala pero esperaba algo mejor",
        likes: 5, 
        comments: 2, 
        rating: 3, 
        date: new Date(),
        username: "mateodev", 
        userId: 5, 
        songId: 2, 
        imageUrl: null,
    },
    {
        content: "Muy relajante, perfecta para escuchar estudiando",
        likes: 11, 
        comments: 1, 
        rating: 4, 
        date: new Date(),
        username: "valentina_21", 
        userId: 6, songId: 3, 
        imageUrl: null,
    },
    {
        content: "Tiene un estilo muy diferente, me gustó bastante",
        likes: 7, 
        comments: 2, 
        rating: 4, 
        date: new Date(),
        username: "juanmusic", 
        userId: 7, 
        songId: 3, 
        imageUrl: null,
    },
    {
        content: "La escuché por recomendación y sí vale la pena",
        likes: 8, 
        comments: 0, 
        rating: 4, 
        date: new Date(),
        username: "danitech", 
        userId: 8, 
        songId: 4, 
        imageUrl: null,
    },
    {
        content: "Muy buena colaboración, suena demasiado bien",
        likes: 14, 
        comments: 3, 
        rating: 5, 
        date: new Date(),
        username: "carlos23", 
        userId: 1, 
        songId: 4, 
        imageUrl: null,
    },
    {
        content: "Al principio no me gustaba pero ahora sí me gusta mucho",
        likes: 10, 
        comments: 1, 
        rating: 4, 
        date: new Date(),
        username: "lauramusic", 
        userId: 2, 
        songId: 4, 
        imageUrl: null,
    },
    {
        content: "La instrumental está demasiado buena",
        likes: 6, 
        comments: 1, 
        rating: 4, 
        date: new Date(),
        username: "andresgamer", 
        userId: 3, 
        songId: 5, 
        imageUrl: null,
    },
    {
        content: "Muy buena canción para escuchar en el carro",
        likes: 9, 
        comments: 0, 
        rating: 4, 
        date: new Date(),
        username: "sofia_r", 
        userId: 4, 
        songId: 5, 
        imageUrl: null,
    },
    {
        content: "Siento que es una de las mejores canciones de este álbum",
        likes: 13, 
        comments: 2, 
        rating: 5, 
        date: new Date(),
        username: "mateodev", 
        userId: 5, 
        songId: 5, 
        imageUrl: null,
    },
    {
        content: "No está mal pero no es de mis favoritas",
        likes: 4, 
        comments: 0, 
        rating: 3, 
        date: new Date(),
        username: "valentina_21", 
        userId: 6, 
        songId: 6, 
        imageUrl: null,
    },
    {
        content: "El ritmo es demasiado bueno, se queda en la cabeza",
        likes: 12, 
        comments: 2, 
        rating: 5, 
        date: new Date(),
        username: "juanmusic", 
        userId: 7, 
        songId: 6, 
        imageUrl: null,
    },
];

export async function loadInitialReviews() {
    try {
        const count = await Review.count();
        if (count === 0) {
            await Review.bulkCreate(initialReviews);
            console.log("Initial reviews loaded");
        } else {
            console.log("Initial reviews already loaded");
        }
    } catch (error) {
        console.log(error);
    }
}